// File generated by FlutterFire (adapted from google-services.json)
// DO NOT EDIT - Regenerate if you need to update Firebase config

import 'dart:io' show Platform;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform, kIsWeb;
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.android)) {
      return android;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIZR4sivQZWc8blwnNkXsbEEnOthcBmH4',
    appId: '1:448659925382:android:8e75b9ddfff5d43ab32407',
    messagingSenderId: '448659925382',
    projectId: 'wesleys-clock',
    storageBucket: 'wesleys-clock.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIZR4sivQZWc8blwnNkXsbEEnOthcBmH4',
    appId: '1:448659925382:web:placeholder',
    messagingSenderId: '448659925382',
    projectId: 'wesleys-clock',
    storageBucket: 'wesleys-clock.firebasestorage.app',
    authDomain: 'wesleys-clock.firebaseapp.com',
  );
}
